[tools]
node = "lts"
bun = "latest"
deno = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:sharkdp/bat" = "latest"
"github:cli/cli" = "latest"
"github:eza-community/eza" = "latest"
"github:jkfran/killport" = "latest"
"github:junegunn/fzf" = "latest"
"github:rossmacarthur/sheldon" = "latest"
"github:starship/starship" = "latest"
"github:suzuki-shunsuke/pinact" = "latest"
"github:sxyazi/yazi" = "latest"
"github:tmux/tmux-builds" = "latest"
"github:x-motemen/ghq" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:editorconfig-checker" = "latest"
"npm:fixpack" = "latest"
"npm:npmrc" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"

[tools."github:jqlang/jq"]
version = "latest"

[tools."github:jqlang/jq".platforms]
macos-x64 = { asset_pattern = "jq-macos-amd64" }
macos-arm64 = { asset_pattern = "jq-macos-arm64" }

[settings]
experimental = true
idiomatic_version_file_enable_tools = ['node']
