[tools]
node = "lts"
bun = "latest"
deno = "latest"
"github:cli/cli" = "latest"
"github:eza-community/eza" = { version = "latest", os = ["linux"] }
"github:jkfran/killport" = "latest"
"github:junegunn/fzf" = "latest"
"github:rossmacarthur/sheldon" = "latest"
"github:starship/starship" = "latest"
"github:suzuki-shunsuke/pinact" = "latest"
"github:x-motemen/ghq" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:editorconfig-checker" = "latest"
"npm:fixpack" = "latest"
"npm:npmrc" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ['node']
