[tools]
node = "lts"
bun = "latest"
deno = "latest"
"github:cli/cli" = "latest"
"github:eza-community/eza" = { version = "latest", os = ["linux"] }
"github:jkfran/killport" = "latest"
"github:junegunn/fzf" = "latest"
"github:rossmacarthur/sheldon" = "latest"
"github:starship/starship" = "latest"
"github:suzuki-shunsuke/pinact" = "latest"
"github:x-motemen/ghq" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:editorconfig-checker" = "latest"
"npm:fixpack" = "latest"
"npm:npmrc" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"

[tools."github:jqlang/jq"]
version = "latest"

[tools."github:jqlang/jq".platforms]
macos-x64 = { asset_pattern = "jq-macos-amd64" }
macos-arm64 = { asset_pattern = "jq-macos-arm64" }
linux-x64 = { asset_pattern = "jq-linux-amd64" }
linux-x64-musl = { asset_pattern = "jq-linux-amd64" }
linux-arm64 = { asset_pattern = "jq-linux-arm64" }
linux-arm64-musl = { asset_pattern = "jq-linux-arm64" }
linux-armv6 = { asset_pattern = "jq-linux-armel" }
linux-armv6-musl = { asset_pattern = "jq-linux-armel" }
linux-armv7 = { asset_pattern = "jq-linux-armhf" }
linux-armv7-musl = { asset_pattern = "jq-linux-armhf" }

[settings]
experimental = true
idiomatic_version_file_enable_tools = ['node']
